//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiDrugWeb1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alertmeeting
    {
        public int alertID { get; set; }
        public System.DateTime alertDate { get; set; }
        public string alertTitle { get; set; }
        public string alertDetail { get; set; }
        public string alertReport { get; set; }
        public string alertByStaff { get; set; }
    }
}
